### ISSUE TITLE
"A kiválasztott Posta Pont átvevőhely:" szöveg ne látszódjon mindig az értesítőkön.

### ISSUE THREAD

**Issue by Attika7777** [passatgt/wc-postapont#1]
Szia!
Köszi nagyon jó kis plugin. :+1: 
Egy apróság:
A rendelési értesítőkön mindig megjelenik ez a sor: "A kiválasztott Posta Pont átvevőhely:"
Akkor is ha nem ezt a szállítási módot választottam. Ez egy kicsit zavaró.
Meg tudnád oldani, hogy ha másik szállítási módot választottam, akkor ne jelenjen meg ez a szöveg a rendelési értesítőkön.
Köszi Attila

**Comment by Zsofia68** [comment]
Szia !
Szuper plugin  már ezt használom a legalább egy éve ! Nagyon szeretjük  mi is és vevők is !!! 

A kérdésem az lenne , hogy most valamilyen okból eltűnt a térképen  posta pont zászlócskák ( vagy hely meghatározó logók ) , így most csak az üres térkép szelvény látható és annak is az része ami számlázási címben szerepel  . Emiatt nem tud  a vevő nagyon a térképen keresgélni másik átvevő pont után ..
Tudnál valamilyen ötletet adni , hogy mi lehet az ok ! 
Illetve kérdezném hátha ..... Webox plugin ?? 
szép napot 
 Zsófi
