### ISSUE TITLE
Felhasználói oldalon nem jelenik meg a plugin

### ISSUE THREAD

**Issue by doriankovacs** [passatgt/wc-postapont#3]
Kedves Péter!

A legfrissebb Wordpress és Woocommerce alá telepítettem a plugint, de sajnos nem jelenik meg a felhasználói oldalon, csak az admin oldalon. Másoktól is hallottam, hogy ugyanezzel a problémával találkoztak, tehát feltehetőleg nem sablon konfliktusról van szól.

Üdv:
Kovács Dorián

**Comment by passatgt** [comment]
Még a héten utánanézek és frissítem, hogy kompatibilis legyen az új WP/WC verziókkal.

**Comment by doriankovacs** [comment]
Köszi Péter! Nagyon várom!! :)

**Comment by passatgt** [comment]
Letesztelnéd az 1.0.2-es verziót? Ha nem megy, valszeg téma kompatibilitás gond lehet, mert gyári témával és új telepítéssel nálam működik.

**Comment by doriankovacs** [comment]
Köszönöm, most már rendben van!
